### ISSUE TITLE
what are all threads doing :)

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/baobzi#31]
Hi Robert,
benchmarking from C, I see:
```
gcc baobzi_timing.c -o baobzi_timing -lbaobzi -lgomp -lm
OMP_NUM_THREADS=1 ./baobzi_timing
OMP_NUM_THREADS=8 ./baobzi_timing
```
give identical timings
(aroud 50 Meval/s 2d and 20 Meval/s 3d on ryzen laptop)
but use all avail threads. OpenMP seems to be a prereq for compilation but I haven't looked in code to see how it's used - seems to be a distraction, is that right? Sorry I'm just randomly trying things.
THanks, Alex

**Comment by blackwer** [comment]
Threads are used for fitting, not for evaluation currently. I should think about adding a proper threading interface, rather than using `OMP_NUM_THREADS`, so you can set it for multieval/fitting.
