### ISSUE TITLE
Description of `center` and `hl` arguments

### ISSUE THREAD

**Issue by janden** [flatironinstitute/baobzi#40]
It's note quite clear what these arguments are from the README. Digging through the header files, I see that `center` is the center of the domain, while `hl` stands for half-length, so I assume that in the 1D case the domain looks like `[center - hl, center + hl]`? Would be good to include this in the README (I guess under “Input parameters”?).

**Comment by blackwer** [comment]
Yeah sorry about this! I've updated it in main, though note that the API is under reconstruction to support vector valued functions, so things are changing

closed by 92aaa11

**Comment by janden** [comment]
Cool. Thanks!
